import { PUBLIC_BACKEND_API_BASE, PUBLIC_CLERK_PUBLISHABLE_KEY, PUBLIC_CLERK_FRONTEND_URL_API, PUBLIC_STRIPE_PUBLIC_KEY, PUBLIC_WEBRTC_ICE_SERVERS, PUBLIC_TURN_SERVERS, PUBLIC_TURN_USERNAME, PUBLIC_TURN_CREDENTIAL } from '$env/static/public';

export const env = {
  backendBase: PUBLIC_BACKEND_API_BASE || '/api',
  clerkPk: PUBLIC_CLERK_PUBLISHABLE_KEY,
  clerkFrontendApi: PUBLIC_CLERK_FRONTEND_URL_API,
  stripePk: PUBLIC_STRIPE_PUBLIC_KEY,
  iceServersJson: PUBLIC_WEBRTC_ICE_SERVERS,
  turn: {
    servers: PUBLIC_TURN_SERVERS,
    username: PUBLIC_TURN_USERNAME,
    credential: PUBLIC_TURN_CREDENTIAL
  }
};