version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SIGNING_SECRET=${STRIPE_WEBHOOK_SIGNING_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - redis
  frontend:
    build:
      context: .
    environment:
      - PUBLIC_BACKEND_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend